import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, resolve } from 'path';
import type { SbomModuleGraphContext, SbomOutputBundleLike, SbomResolvedConfigSlice } from './build-shim.js';
import type { Dependency, PluginOptions } from './types.js';
import { readPackageJson, collectAllDependencies, enrichWithVulnerabilities } from './utils.js';
import { collectBundleDependencies } from './bundle-analyzer.js';
import { generateSPDXJSON } from './spdx-generator.js';
import { generateCycloneDXJSON } from './cyclonedx-generator.js';
import { generateHTMLReport } from './report-generator.js';

/**
 * Структурный тип плагина без привязки к конкретной копии `vite` в node_modules.
 * Совместим с `PluginOption` в конфиге Vite.
 */
export interface VitePluginDtsbomHandle {
  name: string;
  enforce?: 'pre' | 'post';
  configResolved?(config: SbomResolvedConfigSlice): void;
  generateBundle?(
    this: SbomModuleGraphContext,
    options: unknown,
    bundle: SbomOutputBundleLike
  ): void | Promise<void>;
  writeBundle?(): void | Promise<void>;
}

export default function vitePluginDtsbom(options: PluginOptions = {}): VitePluginDtsbomHandle {
  const {
    outputDir = 'sbom',
    spdx = true,
    cyclonedx = true,
    includeDevDependencies = false,
    packageName,
    packageVersion,
    parseNodeModules = true,
    includeTransitiveDependencies = true,
    analysisMode = 'bundle',
    fetchVulnerabilities = true,
    vulnFetchTimeoutMs = 15_000,
    report = true,
    reportFileName = 'sbom-report.html',
  } = options;

  // Whether the user explicitly provided an outputDir (vs relying on the default)
  const userSetOutputDir = 'outputDir' in options;

  let root = '';
  let resolvedBuildOutDir = '';   // Vite's build.outDir (e.g. "dist")
  let packageInfo: ReturnType<typeof readPackageJson> = null;

  async function emitSbom(rawDependencies: Dependency[]) {
    if (!packageInfo) {
      console.warn('[vite-plugin-dtsbom] package.json not found, skipping SBOM generation');
      return;
    }

    // Enrich with live vulnerability data from OSV.dev
    const dependencies = fetchVulnerabilities
      ? await enrichWithVulnerabilities(rawDependencies, { timeoutMs: vulnFetchTimeoutMs })
      : rawDependencies;

    const vulnCount = dependencies.reduce(
      (sum, d) => sum + (d.vulnerabilities?.length ?? 0),
      0
    );
    if (vulnCount > 0) {
      const affected = dependencies.filter(d => d.vulnerabilities?.length);
      console.warn(
        `[vite-plugin-dtsbom] ⚠  Found ${vulnCount} known vulnerabilit${vulnCount === 1 ? 'y' : 'ies'} in ${affected.length} package(s): ` +
          affected.map(d => `${d.name}@${d.version}`).join(', ')
      );
    } else if (fetchVulnerabilities) {
      console.log('[vite-plugin-dtsbom] ✓ No known vulnerabilities found in bundled dependencies.');
    }

    // If the user explicitly passed outputDir — always honour it.
    // Otherwise fall back to Vite's build.outDir so the old default behaviour
    // (outputDir: 'dist') is not silently broken for existing configs.
    const outputPath = resolve(
      root,
      userSetOutputDir ? outputDir : (resolvedBuildOutDir || outputDir)
    );

    if (!existsSync(outputPath)) {
      mkdirSync(outputPath, { recursive: true });
    }

    // Drop a .gitignore so the generated folder is never accidentally committed,
    // regardless of what the user's project .gitignore says.
    const gitignorePath = join(outputPath, '.gitignore');
    if (!existsSync(gitignorePath)) {
      writeFileSync(gitignorePath, '# Auto-generated by vite-plugin-dtsbom — do not commit\n*\n', 'utf-8');
    }

    const genOptions = {
      packageName: packageName || packageInfo.name,
      packageVersion: packageVersion || packageInfo.version,
    };

    if (spdx) {
      const spdxContent = generateSPDXJSON(packageInfo, dependencies, genOptions);
      const spdxPath = join(outputPath, 'sbom.spdx.json');
      writeFileSync(spdxPath, spdxContent, 'utf-8');
      console.log(`[vite-plugin-dtsbom] Generated SPDX SBOM: ${spdxPath}`);
    }

    if (cyclonedx) {
      const cyclonedxContent = generateCycloneDXJSON(packageInfo, dependencies, genOptions);
      const cyclonedxPath = join(outputPath, 'sbom.cyclonedx.json');
      writeFileSync(cyclonedxPath, cyclonedxContent, 'utf-8');
      console.log(`[vite-plugin-dtsbom] Generated CycloneDX SBOM: ${cyclonedxPath}`);
    }

    if (report) {
      const htmlContent = generateHTMLReport(packageInfo, dependencies, genOptions);
      const reportPath = join(outputPath, reportFileName);
      writeFileSync(reportPath, htmlContent, 'utf-8');
      console.log(`[vite-plugin-dtsbom] Generated HTML report:    ${reportPath}`);
    }
  }

  return {
    name: 'vite-plugin-dtsbom',
    enforce: 'post',

    configResolved(config: SbomResolvedConfigSlice) {
      root = config.root;
      resolvedBuildOutDir = config.build.outDir;
      packageInfo = readPackageJson(root);
    },

    async generateBundle(
      this: SbomModuleGraphContext,
      _options: unknown,
      bundle: SbomOutputBundleLike
    ) {
      if (analysisMode !== 'bundle') {
        return;
      }

      try {
        const dependencies = collectBundleDependencies(this, bundle, root);
        await emitSbom(dependencies);
      } catch (error) {
        console.error('[vite-plugin-dtsbom] Error generating SBOM:', error);
      }
    },

    async writeBundle() {
      if (analysisMode !== 'packageGraph') {
        return;
      }

      if (!packageInfo) {
        console.warn('[vite-plugin-dtsbom] package.json not found, skipping SBOM generation');
        return;
      }

      try {
        const dependencies = collectAllDependencies(packageInfo, root, {
          includeDev: includeDevDependencies,
          parseNodeModules,
          includeTransitive: includeTransitiveDependencies,
        });
        await emitSbom(dependencies);
      } catch (error) {
        console.error('[vite-plugin-dtsbom] Error generating SBOM:', error);
      }
    },
  };
}

export type { PluginOptions } from './types.js';
